name: Automated PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install base tools
        run: |
          python -m pip install --upgrade pip
          # Always install requests (needed by the bot)
          pip install requests
          # If requirements.txt exists, install it too
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          # Linters/formatters (best-effort)
          pip install flake8==7.1.0 black==24.8.0 pytest==8.3.2 cpplint==1.6.1 || true
          sudo apt-get update -y || true
          sudo apt-get install -y clang-format || true

          # JS toolchain only if package.json exists
          if [ -f package.json ]; then
            corepack enable || true
            npm ci || npm install --no-audit --no-fund || true
            npx --yes eslint -v || npm i -D eslint || true
            npm i -D prettier || true
          fi

      - name: Run PR review bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          python scripts/pr_review_bot.py
